<?php $mobile = new \App\Classes\Mobile(); ?>
<?php if (!$mobile->isMobile()): ?>

<div style="height:80vh !important; width:100vw !important;">
         <!-- Top Navigation -->
         <!--<div class="codrops-top clearfix">
            <a class="codrops-icon codrops-icon-prev" href="http://tympanus.net/Development/InlineAnchorStyles/"><span>Previous Demo</span></a>
            <span class="right"><a class="codrops-icon codrops-icon-drop" href="http://tympanus.net/codrops/?p=19242"><span>Back to the Codrops Article</span></a></span>
         </div>-->
         <div id="boxgallery" class="boxgallery" data-effect="effect-1">
            <div id="sp-layer-1" class="panel" data-prev-url="background-image: url('https://www.apartamentosierranevada.net/img/miramarski/mobile-full-slide-3.jpg'); background-repeat: no-repeat; background-size: 100% 100%; background-color:none !important;" data-next-url="background-image: url('https://www.apartamentosierranevada.net/img/miramarski/mobile-full-slide-2.jpg'); background-repeat: no-repeat; background-size: 100% 100%; background-color:none !important;" style="background-image: url('https://www.apartamentosierranevada.net/img/miramarski/mobile-full-slide-2.jpg'); background-repeat: no-repeat; background-size: auto 100%; background-color:none !important;"><img src="{{asset('img/miramarski/mobile-full-slide-1.jpg')}}" style="max-width:none !important;" alt="Image 1"/></div>
            <div id="sp-layer-2" class="panel" data-prev-url="background-image: url('https://www.apartamentosierranevada.net/img/miramarski/mobile-full-slide-1.jpg'); background-repeat: no-repeat; background-size: 100% 100%; background-color:none !important;" data-next-url="background-image: url('https://www.apartamentosierranevada.net/img/miramarski/mobile-full-slide-3.jpg'); background-repeat: no-repeat; background-size: 100% 100%; background-color:none !important;" style="background-image: url('https://www.apartamentosierranevada.net/img/miramarski/mobile-full-slide-3.jpg'); background-repeat: no-repeat; background-size: auto 100%; background-color:none !important;"><img src="{{asset('img/miramarski/mobile-full-slide-2.jpg')}}" style="max-width:none !important;" alt="Image 2"/></div>
            <div id="sp-layer-3" class="panel" data-prev-url="background-image: url('https://www.apartamentosierranevada.net/img/miramarski/mobile-full-slide-2.jpg'); background-repeat: no-repeat; background-size: 100% 100%; background-color:none !important;" data-next-url="background-image: url('https://www.apartamentosierranevada.net/img/miramarski/mobile-full-slide-1.jpg'); background-repeat: no-repeat; background-size: 100% 100%; background-color:none !important;" style="background-image: url('https://www.apartamentosierranevada.net/img/miramarski/mobile-full-slide-1.jpg'); background-repeat: no-repeat; background-size: auto 100%; background-color:none !important;"><img src="{{asset('img/miramarski/mobile-full-slide-3.jpg')}}" style="max-width:none !important;" alt="Image 3"/></div>
         </div>
         <header class="codrops-header">
            <p class="sp-layer sp-padding sp-layer-1" data-position="centerCenter" data-vertical="-50" data-show-transition="right" data-hide-transition="left" data-show-delay="500" data-layer-init="true" style="z-index:9999; width: 1200px; margin: auto; right: 0px; white-space: nowrap; bottom: 0px; transform-origin: center center 0px; left: 0px; top: -250px; visibility: visible; opacity: 1; transform: scale(1) translate3d(0px, 0px, 0px); font-family: 'miramar'; font-size:80px; color:#FFFFFF; text-shadow: rgb(0, 0, 0) 1px 1px; white-space: nowrap; line-height: 80px; font-weight:bold; text-align: center; display:none;">
               APARTAMENTOS DE LUJO <br> EN SIERRA NEVADA
            </p>
            <p class="sp-layer sp-padding sp-layer-1" data-position="centerCenter" data-vertical="-50" data-show-transition="right" data-hide-transition="left" data-show-delay="500" data-layer-init="true" style="z-index:9999; margin: auto; right: 0px; white-space: nowrap; bottom: 0px; transform-origin: center center 0px; left: 0px; top: 100px; visibility: visible; opacity: 1; transform: scale(1) translate3d(0px, 0px, 0px); font-family: 'miramar'; font-size:24px; color:#FFFFFF; text-shadow: rgb(0, 0, 0) 1px 1px; white-space: nowrap; text-align: center !important; margin-top: 12px; display:none;">
               SERVICIO EXCLUSIVO<br/> Piscina, gimnasio, parking,guarda<br/> esquis, salida directa a las pistas
            </p>
            <p class="sp-layer sp-padding sp-layer-1" data-position="centerCenter" data-vertical="-50" data-show-transition="right" data-hide-transition="left" data-show-delay="500" data-layer-init="true" style="z-index:9999; width: 800px; margin: auto; right: 0px; white-space: nowrap; bottom: 0px; transform-origin: center center 0px; left: 0px; top: 400px; visibility: visible; opacity: 1; transform: scale(1) translate3d(0px, 0px, 0px); font-family: 'miramar'; font-size:18px; color:#FFFFFF; text-shadow: rgb(0, 0, 0) 1px 1px; white-space: nowrap; line-height: 60px; font-weight:bold; text-align: center; margin-top: 12px; display:none;">
               <button class="tp-caption rev-btn  tp-resizeme btn btn-lg white menu-booking heart font-w300 rs-hover-ready" id="slide-87-layer-7" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['200','200','160','120']" data-width="250" data-height="none" data-whitespace="nowrap" data-type="button" data-actions="" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:1000,&quot;speed&quot;:2000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;sX:0.9;sY:0.9;opacity:0;fb:20px;&quot;,&quot;to&quot;:&quot;o:1;fb:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:500,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;sX:0.9;sY:0.9;opacity:0;fb:20px;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;frame&quot;:&quot;hover&quot;,&quot;speed&quot;:&quot;0&quot;,&quot;ease&quot;:&quot;Linear.easeNone&quot;,&quot;to&quot;:&quot;o:1;rX:0;rY:0;rZ:0;z:0;fb:0;&quot;,&quot;style&quot;:&quot;c:rgba(255,255,255,1);bs:solid;bw:0 0 0 0;&quot;}]" data-textalign="['center','center','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[20,20,20,20]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[20,20,20,20]" style="z-index: 21; white-space: nowrap; background-color: rgb(89, 186, 65); border-radius: 0px; padding: 0px 14px; font-size: 15px; letter-spacing: -1px; text-shadow: rgb(0, 0, 0) 1px 1px; line-height: 43px; outline: currentcolor none medium; box-shadow: rgb(153, 153, 153) 0px 0px 0px 0px; box-sizing: border-box; cursor: pointer; text-decoration: none; visibility: inherit; transition: none 0s ease 0s; text-align: center; margin: 0px; font-weight: 300; min-height: 0px; min-width: 178px; max-height: none; max-width: 178px; transform: translate3d(0px, 0px, 0px) scale(0.9, 0.9); transform-origin: 50% 50% 0px; color: rgb(255, 255, 255);">
                  SOLICITA TU <span class="font-w800" style="transition: none 0s ease 0s; text-align: inherit; line-height: 31px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: -1px; font-weight: 800; /*font-size: 11px;*/">RESERVA</span>
               </button>
            </p>
            <p class="sp-layer sp-padding sp-layer-2" data-position="centerCenter" data-vertical="-50" data-show-transition="right" data-hide-transition="left" data-show-delay="500" data-layer-init="true" style="z-index:9999; width: 1200px; margin: auto; right: 0px; white-space: nowrap; bottom: 0px; transform-origin: center center 0px; left: 0px; top: -250px; visibility: visible; opacity: 1; transform: scale(1) translate3d(0px, 0px, 0px); font-family: 'miramar'; font-size:80px; color:#FFFFFF; text-shadow: rgb(0, 0, 0) 1px 1px; white-space: nowrap; line-height: 80px; font-weight:bold; text-align: center; display:none;">
               A PIE DE PISTA <br> SIN COGER REMONTES
            </p>
            <p class="sp-layer sp-padding sp-layer-2" data-position="centerCenter" data-vertical="-50" data-show-transition="right" data-hide-transition="left" data-show-delay="500" data-layer-init="true" style="z-index:9999; margin: auto; right: 0px; white-space: nowrap; bottom: 0px; transform-origin: center center 0px; left: 0px; top: 100px; visibility: visible; opacity: 1; transform: scale(1) translate3d(0px, 0px, 0px); font-family: 'miramar'; font-size:24px; color:#FFFFFF; text-shadow: rgb(0, 0, 0) 1px 1px; white-space: nowrap; text-align: center !important; margin-top: 12px; display:none;">
               Uno de los edificios más modernos de<br/> Sierra Nevada.
            </p>
            <p class="sp-layer sp-padding sp-layer-2" data-position="centerCenter" data-vertical="-50" data-show-transition="right" data-hide-transition="left" data-show-delay="500" data-layer-init="true" style="z-index:9999; width: 800px; margin: auto; right: 0px; white-space: nowrap; bottom: 0px; transform-origin: center center 0px; left: 0px; top: 400px; visibility: visible; opacity: 1; transform: scale(1) translate3d(0px, 0px, 0px); font-family: 'miramar'; font-size:18px; color:#FFFFFF; text-shadow: rgb(0, 0, 0) 1px 1px; white-space: nowrap; line-height: 60px; font-weight:bold; text-align: center; margin-top: 12px; display:none;">
               <button class="tp-caption rev-btn  tp-resizeme btn btn-lg white menu-booking heart font-w300 rs-hover-ready" id="slide-87-layer-7" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['200','200','160','120']" data-width="250" data-height="none" data-whitespace="nowrap" data-type="button" data-actions="" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:1000,&quot;speed&quot;:2000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;sX:0.9;sY:0.9;opacity:0;fb:20px;&quot;,&quot;to&quot;:&quot;o:1;fb:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:500,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;sX:0.9;sY:0.9;opacity:0;fb:20px;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;frame&quot;:&quot;hover&quot;,&quot;speed&quot;:&quot;0&quot;,&quot;ease&quot;:&quot;Linear.easeNone&quot;,&quot;to&quot;:&quot;o:1;rX:0;rY:0;rZ:0;z:0;fb:0;&quot;,&quot;style&quot;:&quot;c:rgba(255,255,255,1);bs:solid;bw:0 0 0 0;&quot;}]" data-textalign="['center','center','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[20,20,20,20]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[20,20,20,20]" style="z-index: 21; white-space: nowrap; background-color: rgb(89, 186, 65); border-radius: 0px; padding: 0px 14px; font-size: 15px; letter-spacing: -1px; text-shadow: rgb(0, 0, 0) 1px 1px; line-height: 43px; outline: currentcolor none medium; box-shadow: rgb(153, 153, 153) 0px 0px 0px 0px; box-sizing: border-box; cursor: pointer; text-decoration: none; visibility: inherit; transition: none 0s ease 0s; text-align: center; margin: 0px; font-weight: 300; min-height: 0px; min-width: 178px; max-height: none; max-width: 178px; transform: translate3d(0px, 0px, 0px) scale(0.9, 0.9); transform-origin: 50% 50% 0px; color: rgb(255, 255, 255);">
                  SOLICITA TU <span class="font-w800" style="transition: none 0s ease 0s; text-align: inherit; line-height: 31px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: -1px; font-weight: 800; /*font-size: 11px;*/">RESERVA</span>
               </button>
            </p>
            <p class="sp-layer sp-padding sp-layer-3" data-position="centerCenter" data-vertical="-50" data-show-transition="right" data-hide-transition="left" data-show-delay="500" data-layer-init="true" style="z-index:9999; width: 1200px; margin: auto; right: 0px; white-space: nowrap; bottom: 0px; transform-origin: center center 0px; left: 0px; top: -250px; visibility: visible; opacity: 1; transform: scale(1) translate3d(0px, 0px, 0px); font-family: 'miramar'; font-size:80px; color:#FFFFFF; text-shadow: rgb(0, 0, 0) 1px 1px; white-space: nowrap; line-height: 80px; font-weight:bold; text-align: center; display:none;">
               UNA EXPERIENCIA INOLVIDABLE
            </p>
            <p class="sp-layer sp-padding sp-layer-3" data-position="centerCenter" data-vertical="-50" data-show-transition="right" data-hide-transition="left" data-show-delay="500" data-layer-init="true" style="z-index:9999; margin: auto; right: 0px; white-space: nowrap; bottom: 0px; transform-origin: center center 0px; left: 0px; top: 100px; visibility: visible; opacity: 1; transform: scale(1) translate3d(0px, 0px, 0px); font-family: 'miramar'; font-size:24px; color:#FFFFFF; text-shadow: rgb(0, 0, 0) 1px 1px; white-space: nowrap; text-align: center !important; margin-top: 12px; display:none;">
               Piscina climatizada, gimnasio, parking<br/> cubierto, taquilla guardaesquis, acceso<br/> directo a las pistas
            </p>
            <p class="sp-layer sp-padding sp-layer-3" data-position="centerCenter" data-vertical="-50" data-show-transition="right" data-hide-transition="left" data-show-delay="500" data-layer-init="true" style="z-index:9999; width: 800px; margin: auto; right: 0px; white-space: nowrap; bottom: 0px; transform-origin: center center 0px; left: 0px; top: 400px; visibility: visible; opacity: 1; transform: scale(1) translate3d(0px, 0px, 0px); font-family: 'miramar'; font-size:18px; color:#FFFFFF; text-shadow: rgb(0, 0, 0) 1px 1px; white-space: nowrap; line-height: 60px; font-weight:bold; text-align: center; margin-top: 12px; display:none;">
               <button class="tp-caption rev-btn  tp-resizeme btn btn-lg white menu-booking heart font-w300 rs-hover-ready" id="slide-87-layer-7" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['200','200','160','120']" data-width="250" data-height="none" data-whitespace="nowrap" data-type="button" data-actions="" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:1000,&quot;speed&quot;:2000,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;sX:0.9;sY:0.9;opacity:0;fb:20px;&quot;,&quot;to&quot;:&quot;o:1;fb:0;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:500,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;sX:0.9;sY:0.9;opacity:0;fb:20px;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;frame&quot;:&quot;hover&quot;,&quot;speed&quot;:&quot;0&quot;,&quot;ease&quot;:&quot;Linear.easeNone&quot;,&quot;to&quot;:&quot;o:1;rX:0;rY:0;rZ:0;z:0;fb:0;&quot;,&quot;style&quot;:&quot;c:rgba(255,255,255,1);bs:solid;bw:0 0 0 0;&quot;}]" data-textalign="['center','center','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[20,20,20,20]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[20,20,20,20]" style="z-index: 21; white-space: nowrap; background-color: rgb(89, 186, 65); border-radius: 0px; padding: 0px 14px; font-size: 15px; letter-spacing: -1px; text-shadow: rgb(0, 0, 0) 1px 1px; line-height: 43px; outline: currentcolor none medium; box-shadow: rgb(153, 153, 153) 0px 0px 0px 0px; box-sizing: border-box; cursor: pointer; text-decoration: none; visibility: inherit; transition: none 0s ease 0s; text-align: center; margin: 0px; font-weight: 300; min-height: 0px; min-width: 178px; max-height: none; max-width: 178px; transform: translate3d(0px, 0px, 0px) scale(0.9, 0.9); transform-origin: 50% 50% 0px; color: rgb(255, 255, 255);">
                  SOLICITA TU <span class="font-w800" style="transition: none 0s ease 0s; text-align: inherit; line-height: 31px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: -1px; font-weight: 800; /*font-size: 11px;*/">RESERVA</span>
               </button>
            </p>
            {{--<h1>Four Boxes Slideshow <span>Recreating the background image slideshow seen on <a href="http://www.atelier-serge-thoraval.com/en/">Atelier Serge Thoroval's website</a></span></h1>
            <nav class="codrops-demos">
               <a href="index.html">Serge Thoroval</a>
               <a class="current-demo" href="index2.html">Lateral</a>
               <a href="index3.html">Fall</a>
            </nav>--}}
         </header>
 </div>

<?php else: ?>

<div style="height:70vh !important; width:100vw !important;">
         <!-- Top Navigation -->
         <!--<div class="codrops-top clearfix">
            <a class="codrops-icon codrops-icon-prev" href="http://tympanus.net/Development/InlineAnchorStyles/"><span>Previous Demo</span></a>
            <span class="right"><a class="codrops-icon codrops-icon-drop" href="http://tympanus.net/codrops/?p=19242"><span>Back to the Codrops Article</span></a></span>
         </div>-->
         <div id="boxgallery" class="boxgallery" data-effect="effect-1">
            
            <div id="sp-layer-1" class="panel" data-prev-url="background-image: url('https://www.apartamentosierranevada.net/img/miramarski/mobile-full-slide-3.jpg'); background-repeat: no-repeat; background-size: cover; background-position: center center; width: 100%; height: 100%; opacity: 1; visibility: inherit; background-color:none !important;" data-next-url="background-image: url('https://www.apartamentosierranevada.net/img/miramarski/mobile-full-slide-2.jpg'); background-repeat: no-repeat; background-size: cover; background-position: center center; width: 100%; height: 100%; opacity: 1; visibility: inherit; background-color:none !important;" style="background-image: url('https://www.apartamentosierranevada.net/img/miramarski/mobile-full-slide-2.jpg'); background-repeat: no-repeat; background-size: cover; background-position: center center; width: 100%; height: 100%; opacity: 1; visibility: inherit; background-color:none !important;"><img src="{{asset('img/miramarski/mobile-full-slide-1.jpg')}}" style="max-width:none !important;" alt="Image 1"/></div>
            <div id="sp-layer-2" class="panel" data-prev-url="background-image: url('https://www.apartamentosierranevada.net/img/miramarski/mobile-full-slide-1.jpg'); background-repeat: no-repeat; background-size: cover; background-position: center center; width: 100%; height: 100%; opacity: 1; visibility: inherit; background-color:none !important;" data-next-url="background-image: url('https://www.apartamentosierranevada.net/img/miramarski/mobile-full-slide-3.jpg'); background-repeat: no-repeat; background-size: cover; background-position: center center; width: 100%; height: 100%; opacity: 1; visibility: inherit; background-color:none !important;" style="background-image: url('https://www.apartamentosierranevada.net/img/miramarski/mobile-full-slide-3.jpg'); background-repeat: no-repeat; background-size: cover; background-position: center center; width: 100%; height: 100%; opacity: 1; visibility: inherit; background-color:none !important;"><img src="{{asset('img/miramarski/mobile-full-slide-2.jpg')}}" style="max-width:none !important;" alt="Image 2"/></div>
            <div id="sp-layer-3" class="panel" data-prev-url="background-image: url('https://www.apartamentosierranevada.net/img/miramarski/mobile-full-slide-2.jpg'); background-repeat: no-repeat; background-size: cover; background-position: center center; width: 100%; height: 100%; opacity: 1; visibility: inherit; background-color:none !important;" data-next-url="background-image: url('https://www.apartamentosierranevada.net/img/miramarski/mobile-full-slide-1.jpg'); background-repeat: no-repeat; background-size: cover; background-position: center center; width: 100%; height: 100%; opacity: 1; visibility: inherit; background-color:none !important;" style="background-image: url('https://www.apartamentosierranevada.net/img/miramarski/mobile-full-slide-1.jpg'); background-repeat: no-repeat; background-size: cover; background-position: center center; width: 100%; height: 100%; opacity: 1; visibility: inherit; background-color:none !important;"><img src="{{asset('img/miramarski/mobile-full-slide-3.jpg')}}" style="max-width:none !important;" alt="Image 3"/></div>
         </div>
         <header class="codrops-header">
            <p class="sp-layer sp-padding sp-layer-1" data-position="centerCenter" data-vertical="-50" data-show-transition="right" data-hide-transition="left" data-show-delay="500" data-layer-init="true" style="z-index:9999; margin: auto; right: 0px; white-space: nowrap; bottom: 0px; transform-origin: center center 0px; left: 0px; top: -250px; visibility: visible; opacity: 1; transform: scale(1) translate3d(0px, 0px, 0px); font-family: 'miramar'; font-size:10.8vw; color:#FFFFFF; text-shadow: rgb(0, 0, 0) 1px 1px; white-space: nowrap; line-height: 40px; font-weight:bold; text-align: center; margin-bottom: 10px; display:none;">
               APARTAMENTOS<br/> DE LUJO
            </p>
            <p class="sp-layer sp-padding sp-layer-1" data-position="centerCenter" data-vertical="-50" data-show-transition="right" data-hide-transition="left" data-show-delay="500" data-layer-init="true" style="z-index:9999; margin: auto; right: 0px; white-space: nowrap; bottom: 0px; transform-origin: center center 0px; left: 0px; top: 100px; visibility: visible; opacity: 1; transform: scale(1) translate3d(0px, 0px, 0px); font-family: 'miramar'; font-size:2.5vh; color:#FFFFFF; text-shadow: rgb(0, 0, 0) 1px 1px; white-space: nowrap; text-align: center !important; font-weight:bold; display:none;">
               SERVICIO EXCLUSIVO<br/> Piscina, gimnasio, parking,guarda<br/> esquis, salida directa a las pistas
            </p>
            <p class="sp-layer sp-padding sp-layer-1" data-position="centerCenter" data-vertical="-50" data-show-transition="right" data-hide-transition="left" data-show-delay="500" data-layer-init="true" style="z-index:9999; margin: auto; right: 0px; white-space: nowrap; bottom: 0px; transform-origin: center center 0px; left: 0px; top: 400px; visibility: visible; opacity: 1; transform: scale(1) translate3d(0px, 0px, 0px); font-family: 'miramar'; font-size:18px; color:#FFFFFF; text-shadow: rgb(0, 0, 0) 1px 1px; white-space: nowrap; line-height: 60px; font-weight:bold; text-align: center; margin-top: 12px; display:none;">
               <button class="tp-caption rev-btn  tp-resizeme btn btn-xs white menu-booking heart font-w300" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['70','40','100','100']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="button" data-actions=''data-responsive_offset="on" data-frames='[{"delay":1000,"speed":1000,"frame":"0","from":"y:-20px;opacity:0;fb:10px;","to":"o:1;fb:0;","ease":"Power4.easeOut"},{"delay":"wait","speed":600,"frame":"999","to":"auto:auto;fb:0;","ease":"Power3.easeInOut"},{"frame":"hover","speed":"200","ease":"Linear.easeNone","to":"o:1;rX:0;rY:0;rZ:0;z:0;fb:0;","style":"c:rgba(255, 255, 255, 1.00);bg:rgba(45, 48, 50, 1.00);bs:solid;bw:0 0 0 0;"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[35,35,35,35]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[35,35,35,35]" style="z-index: 12; white-space: nowrap; font-size: 20px; /*line-height: 50px;*/ font-weight:700; color: rgba(45, 48, 50, 1.00);font-family:'miramar';background-color:rgb(89, 186, 65);border-color:rgb(89, 186, 65);outline:none;box-shadow:none;box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;text-decoration: none; font-size:14px !important; padding: 0px 35px; !important;">SOLICITA TU <b>RESERVA</b></button>
            </p>
            <p class="sp-layer sp-padding sp-layer-2" data-position="centerCenter" data-vertical="-50" data-show-transition="right" data-hide-transition="left" data-show-delay="500" data-layer-init="true" style="z-index:9999; margin: auto; right: 0px; white-space: nowrap; bottom: 0px; transform-origin: center center 0px; left: 0px; top: -250px; visibility: visible; opacity: 1; transform: scale(1) translate3d(0px, 0px, 0px); font-family: 'miramar'; font-size:7.5vw; color:#FFFFFF; text-shadow: rgb(0, 0, 0) 1px 1px; white-space: nowrap; line-height: 40px; font-weight:bold; text-align: center; margin-bottom: 10px; display:none;">
               A PIE DE PISTA <br> SIN COGER REMONTES
            </p>
            <p class="sp-layer sp-padding sp-layer-2" data-position="centerCenter" data-vertical="-50" data-show-transition="right" data-hide-transition="left" data-show-delay="500" data-layer-init="true" style="z-index:9999; margin: auto; right: 0px; white-space: nowrap; bottom: 0px; transform-origin: center center 0px; left: 0px; top: 100px; visibility: visible; opacity: 1; transform: scale(1) translate3d(0px, 0px, 0px); font-family: 'miramar'; font-size:2.5vh; color:#FFFFFF; text-shadow: rgb(0, 0, 0) 1px 1px; white-space: nowrap; text-align: center !important; font-weight:bold; display:none;">
               Uno de los edificios más modernos de<br/> Sierra Nevada.
            </p>
            <p class="sp-layer sp-padding sp-layer-2" data-position="centerCenter" data-vertical="-50" data-show-transition="right" data-hide-transition="left" data-show-delay="500" data-layer-init="true" style="z-index:9999; margin: auto; right: 0px; white-space: nowrap; bottom: 0px; transform-origin: center center 0px; left: 0px; top: 400px; visibility: visible; opacity: 1; transform: scale(1) translate3d(0px, 0px, 0px); font-family: 'miramar'; font-size:18px; color:#FFFFFF; text-shadow: rgb(0, 0, 0) 1px 1px; white-space: nowrap; line-height: 60px; font-weight:bold; text-align: center; margin-top: 12px; display:none;">
               <button class="tp-caption rev-btn  tp-resizeme btn btn-xs white menu-booking heart font-w300" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['70','40','100','100']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="button" data-actions=''data-responsive_offset="on" data-frames='[{"delay":1000,"speed":1000,"frame":"0","from":"y:-20px;opacity:0;fb:10px;","to":"o:1;fb:0;","ease":"Power4.easeOut"},{"delay":"wait","speed":600,"frame":"999","to":"auto:auto;fb:0;","ease":"Power3.easeInOut"},{"frame":"hover","speed":"200","ease":"Linear.easeNone","to":"o:1;rX:0;rY:0;rZ:0;z:0;fb:0;","style":"c:rgba(255, 255, 255, 1.00);bg:rgba(45, 48, 50, 1.00);bs:solid;bw:0 0 0 0;"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[35,35,35,35]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[35,35,35,35]" style="z-index: 12; white-space: nowrap; font-size: 20px; /*line-height: 50px;*/ line-height: 50px; font-weight:700; color: rgba(45, 48, 50, 1.00);font-family:'miramar';background-color:rgb(89, 186, 65);border-color:rgb(89, 186, 65);outline:none;box-shadow:none;box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;text-decoration: none; font-size:14px !important; padding: 0px 35px; !important;">SOLICITA TU <b>RESERVA</b></button>
            </p>
            <p class="sp-layer sp-padding sp-layer-3" data-position="centerCenter" data-vertical="-50" data-show-transition="right" data-hide-transition="left" data-show-delay="500" data-layer-init="true" style="z-index:9999; margin: auto; right: 0px; white-space: nowrap; bottom: 0px; transform-origin: center center 0px; left: 0px; top: -250px; visibility: visible; opacity: 1; transform: scale(1) translate3d(0px, 0px, 0px); font-family: 'miramar'; font-size:10.8vw; color:#FFFFFF; text-shadow: rgb(0, 0, 0) 1px 1px; white-space: nowrap; line-height: 40px; font-weight:bold; text-align: center; margin-bottom: 10px; display:none;">
               UNA<br/> EXPERIENCIA<br/> INOLVIDABLE
            </p>
            <p class="sp-layer sp-padding sp-layer-3" data-position="centerCenter" data-vertical="-50" data-show-transition="right" data-hide-transition="left" data-show-delay="500" data-layer-init="true" style="z-index:9999; margin: auto; right: 0px; white-space: nowrap; bottom: 0px; transform-origin: center center 0px; left: 0px; top: 100px; visibility: visible; opacity: 1; transform: scale(1) translate3d(0px, 0px, 0px); font-family: 'miramar'; font-size:2.5vh; color:#FFFFFF; text-shadow: rgb(0, 0, 0) 1px 1px; white-space: nowrap; text-align: center !important; font-weight:bold; display:none;">
               Piscina climatizada, gimnasio, parking<br/> cubierto, taquilla guardaesquis, acceso<br/> directo a las pistas
            </p>
            <p class="sp-layer sp-padding sp-layer-3" data-position="centerCenter" data-vertical="-50" data-show-transition="right" data-hide-transition="left" data-show-delay="500" data-layer-init="true" style="z-index:9999; margin: auto; right: 0px; white-space: nowrap; bottom: 0px; transform-origin: center center 0px; left: 0px; top: 400px; visibility: visible; opacity: 1; transform: scale(1) translate3d(0px, 0px, 0px); font-family: 'miramar'; font-size:18px; color:#FFFFFF; text-shadow: rgb(0, 0, 0) 1px 1px; white-space: nowrap; line-height: 60px; font-weight:bold; text-align: center; margin-top: 12px; display:none;">
               <button class="tp-caption rev-btn  tp-resizeme btn btn-xs white menu-booking heart font-w300" data-x="['center','center','center','center']" data-hoffset="['0','0','0','0']" data-y="['middle','middle','middle','middle']" data-voffset="['70','40','100','100']" data-width="none" data-height="none" data-whitespace="nowrap" data-type="button" data-actions=''data-responsive_offset="on" data-frames='[{"delay":1000,"speed":1000,"frame":"0","from":"y:-20px;opacity:0;fb:10px;","to":"o:1;fb:0;","ease":"Power4.easeOut"},{"delay":"wait","speed":600,"frame":"999","to":"auto:auto;fb:0;","ease":"Power3.easeInOut"},{"frame":"hover","speed":"200","ease":"Linear.easeNone","to":"o:1;rX:0;rY:0;rZ:0;z:0;fb:0;","style":"c:rgba(255, 255, 255, 1.00);bg:rgba(45, 48, 50, 1.00);bs:solid;bw:0 0 0 0;"}]' data-textAlign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[35,35,35,35]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[35,35,35,35]" style="z-index: 12; white-space: nowrap; font-size: 20px; /*line-height: 50px;*/ line-height: 50px; font-weight:700; color: rgba(45, 48, 50, 1.00);font-family:'miramar';background-color:rgb(89, 186, 65);border-color:rgb(89, 186, 65);outline:none;box-shadow:none;box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;cursor:pointer;text-decoration: none; font-size:14px !important; padding: 0px 35px; !important;">SOLICITA TU <b>RESERVA</b></button>
            </p>
            {{--<h1>Four Boxes Slideshow <span>Recreating the background image slideshow seen on <a href="http://www.atelier-serge-thoraval.com/en/">Atelier Serge Thoroval's website</a></span></h1>
            <nav class="codrops-demos">
               <a href="index.html">Serge Thoroval</a>
               <a class="current-demo" href="index2.html">Lateral</a>
               <a href="index3.html">Fall</a>
            </nav>--}}
         </header>
 </div>

<?php endif; ?>

<div id="blank_loader" style="height: 105vh !important; width: 100vw !important; background-color: #FFFFFF; position: absolute; z-index: 20000; top: 0;">

</div>




