<?php

function xmlTest()
    {
      return "<?xml version='1.0'?>
<methodResponse>
<params>
<param>
<value><array><data>
<value><int>0</int></value>
<value><array><data>
<value><struct>
<member>
<name>id_channel</name>
<value><int>2</int></value>
</member>
<member>
<name>special_offer</name>
<value><string></string></value>
</member>
<member>
<name>reservation_code</name>
<value><int>1578515999</int></value>
</member>
<member>
<name>dayprices</name>
<value><struct>
<member>
<name>431916</name>
<value><array><data>
<value><double>540.0</double></value>
<value><double>390.0</double></value>
<value><double>390.0</double></value>
<value><double>390.0</double></value>
<value><double>390.0</double></value>
<value><double>390.0</double></value>
<value><double>0.0</double></value>
</data></array></value>
</member>
</struct></value>
</member>
<member>
<name>arrival_hour</name>
<value><string>--</string></value>
</member>
<member>
<name>currency</name>
<value><string>EUR</string></value>
</member>
<member>
<name>booked_rate</name>
<value><int>0</int></value>
</member>
<member>
<name>rooms</name>
<value><string>431916</string></value>
</member>
<member>
<name>customer_mail</name>
<value><string></string></value>
</member>
<member>
<name>customer_country</name>
<value><string>--</string></value>
</member>
<member>
<name>children</name>
<value><int>0</int></value>
</member>
<member>
<name>payment_gateway_fee</name>
<value><string></string></value>
</member>
<member>
<name>modified_reservations</name>
<value><array><data>
</data></array></value>
</member>
<member>
<name>customer_surname</name>
<value><string>Skousen</string></value>
</member>
<member>
<name>date_received_time</name>
<value><string>08/01/2020 21:39:59</string></value>
</member>
<member>
<name>rooms_occupancies</name>
<value><array><data>
<value><struct>
<member>
<name>id</name>
<value><int>431916</int></value>
</member>
<member>
<name>occupancy</name>
<value><int>7</int></value>
</member>
</struct></value>
</data></array></value>
</member>
<member>
<name>date_departure</name>
<value><string>15/02/2020</string></value>
</member>
<member>
<name>amount_reason</name>
<value><string></string></value>
</member>
<member>
<name>customer_city</name>
<value><string></string></value>
</member>
<member>
<name>opportunities</name>
<value><int>0</int></value>
</member>
<member>
<name>date_received</name>
<value><string>08/01/2020</string></value>
</member>
<member>
<name>was_modified</name>
<value><int>0</int></value>
</member>
<member>
<name>sessionSeed</name>
<value><string></string></value>
</member>
<member>
<name>booked_rooms</name>
<value><array><data>
<value><struct>
<member>
<name>ancillary</name>
<value><struct>
<member>
<name>channel_room_id</name>
<value><int>294200801</int></value>
</member>
<member>
<name>addons</name>
<value><array><data>
</data></array></value>
</member>
<member>
<name>guests</name>
<value><int>7</int></value>
</member>
</struct></value>
</member>
<member>
<name>roomdays</name>
<value><array><data>
<value><struct>
<member>
<name>ancillary</name>
<value><struct>
<member>
<name>channel_rate_name</name>
<value><string>Standard Rate</string></value>
</member>
</struct></value>
</member>
<member>
<name>rate_id</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>540.0</double></value>
</member>
<member>
<name>day</name>
<value><string>08/02/2020</string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>ancillary</name>
<value><struct>
<member>
<name>channel_rate_name</name>
<value><string>Standard Rate</string></value>
</member>
</struct></value>
</member>
<member>
<name>rate_id</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>390.0</double></value>
</member>
<member>
<name>day</name>
<value><string>09/02/2020</string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>ancillary</name>
<value><struct>
<member>
<name>channel_rate_name</name>
<value><string>Standard Rate</string></value>
</member>
</struct></value>
</member>
<member>
<name>rate_id</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>390.0</double></value>
</member>
<member>
<name>day</name>
<value><string>10/02/2020</string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>ancillary</name>
<value><struct>
<member>
<name>channel_rate_name</name>
<value><string>Standard Rate</string></value>
</member>
</struct></value>
</member>
<member>
<name>rate_id</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>390.0</double></value>
</member>
<member>
<name>day</name>
<value><string>11/02/2020</string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>ancillary</name>
<value><struct>
<member>
<name>channel_rate_name</name>
<value><string>Standard Rate</string></value>
</member>
</struct></value>
</member>
<member>
<name>rate_id</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>390.0</double></value>
</member>
<member>
<name>day</name>
<value><string>12/02/2020</string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>ancillary</name>
<value><struct>
<member>
<name>channel_rate_name</name>
<value><string>Standard Rate</string></value>
</member>
</struct></value>
</member>
<member>
<name>rate_id</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>390.0</double></value>
</member>
<member>
<name>day</name>
<value><string>13/02/2020</string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>ancillary</name>
<value><struct>
<member>
<name>channel_rate_name</name>
<value><string>Standard Rate</string></value>
</member>
</struct></value>
</member>
<member>
<name>rate_id</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>0.0</double></value>
</member>
<member>
<name>day</name>
<value><string>14/02/2020</string></value>
</member>
</struct></value>
</data></array></value>
</member>
<member>
<name>room_id</name>
<value><int>431916</int></value>
</member>
</struct></value>
</data></array></value>
</member>
<member>
<name>customer_name</name>
<value><string>Anne Mette</string></value>
</member>
<member>
<name>date_arrival</name>
<value><string>08/02/2020</string></value>
</member>
<member>
<name>status</name>
<value><int>1</int></value>
</member>
<member>
<name>channel_data</name>
<value><struct>
<member>
<name>addons_embedded</name>
<value><boolean>1</boolean></value>
</member>
<member>
<name>vat_included</name>
<value><int>-1</int></value>
</member>
</struct></value>
</member>
<member>
<name>channel_reservation_code</name>
<value><string>3619048800</string></value>
</member>
<member>
<name>customer_phone</name>
<value><string></string></value>
</member>
<member>
<name>orig_amount</name>
<value><double>2490.0</double></value>
</member>
<member>
<name>men</name>
<value><int>7</int></value>
</member>
<member>
<name>customer_notes</name>
<value><string></string></value>
</member>
<member>
<name>customer_address</name>
<value><string></string></value>
</member>
<member>
<name>device</name>
<value><int>-1</int></value>
</member>
<member>
<name>addons_list</name>
<value><array><data>
</data></array></value>
</member>
<member>
<name>status_reason</name>
<value><string></string></value>
</member>
<member>
<name>roomnight</name>
<value><int>63</int></value>
</member>
<member>
<name>boards</name>
<value><string></string></value>
</member>
<member>
<name>customer_language</name>
<value><int>2</int></value>
</member>
<member>
<name>fount</name>
<value><string></string></value>
</member>
<member>
<name>customer_zip</name>
<value><string></string></value>
</member>
<member>
<name>amount</name>
<value><double>2490.0</double></value>
</member>
<member>
<name>id_woodoo</name>
<value><int>169684</int></value>
</member>
<member>
<name>cc_info</name>
<value><int>0</int></value>
</member>
<member>
<name>room_opportunities</name>
<value><int>0</int></value>
</member>
<member>
<name>customer_language_iso</name>
<value><string>en</string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>id_channel</name>
<value><int>2</int></value>
</member>
<member>
<name>special_offer</name>
<value><string></string></value>
</member>
<member>
<name>reservation_code</name>
<value><int>1578515998</int></value>
</member>
<member>
<name>dayprices</name>
<value><struct>
<member>
<name>431916</name>
<value><array><data>
<value><double>595.0</double></value>
<value><double>595.0</double></value>
<value><double>390.0</double></value>
<value><double>390.0</double></value>
</data></array></value>
</member>
</struct></value>
</member>
<member>
<name>arrival_hour</name>
<value><string>--</string></value>
</member>
<member>
<name>currency</name>
<value><string>EUR</string></value>
</member>
<member>
<name>booked_rate</name>
<value><int>0</int></value>
</member>
<member>
<name>rooms</name>
<value><string>431916</string></value>
</member>
<member>
<name>customer_mail</name>
<value><string></string></value>
</member>
<member>
<name>customer_country</name>
<value><string>--</string></value>
</member>
<member>
<name>children</name>
<value><int>0</int></value>
</member>
<member>
<name>payment_gateway_fee</name>
<value><string></string></value>
</member>
<member>
<name>modified_reservations</name>
<value><array><data>
</data></array></value>
</member>
<member>
<name>customer_surname</name>
<value><string>Escanellas Genovard</string></value>
</member>
<member>
<name>date_received_time</name>
<value><string>08/01/2020 21:39:58</string></value>
</member>
<member>
<name>rooms_occupancies</name>
<value><array><data>
<value><struct>
<member>
<name>id</name>
<value><int>431916</int></value>
</member>
<member>
<name>occupancy</name>
<value><int>8</int></value>
</member>
</struct></value>
</data></array></value>
</member>
<member>
<name>date_departure</name>
<value><string>03/03/2020</string></value>
</member>
<member>
<name>amount_reason</name>
<value><string></string></value>
</member>
<member>
<name>customer_city</name>
<value><string></string></value>
</member>
<member>
<name>opportunities</name>
<value><int>0</int></value>
</member>
<member>
<name>date_received</name>
<value><string>08/01/2020</string></value>
</member>
<member>
<name>was_modified</name>
<value><int>0</int></value>
</member>
<member>
<name>sessionSeed</name>
<value><string></string></value>
</member>
<member>
<name>booked_rooms</name>
<value><array><data>
<value><struct>
<member>
<name>ancillary</name>
<value><struct>
<member>
<name>channel_room_id</name>
<value><int>294200801</int></value>
</member>
<member>
<name>addons</name>
<value><array><data>
</data></array></value>
</member>
<member>
<name>guests</name>
<value><int>8</int></value>
</member>
</struct></value>
</member>
<member>
<name>roomdays</name>
<value><array><data>
<value><struct>
<member>
<name>ancillary</name>
<value><struct>
<member>
<name>channel_rate_name</name>
<value><string>Standard Rate</string></value>
</member>
</struct></value>
</member>
<member>
<name>rate_id</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>595.0</double></value>
</member>
<member>
<name>day</name>
<value><string>28/02/2020</string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>ancillary</name>
<value><struct>
<member>
<name>channel_rate_name</name>
<value><string>Standard Rate</string></value>
</member>
</struct></value>
</member>
<member>
<name>rate_id</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>595.0</double></value>
</member>
<member>
<name>day</name>
<value><string>29/02/2020</string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>ancillary</name>
<value><struct>
<member>
<name>channel_rate_name</name>
<value><string>Standard Rate</string></value>
</member>
</struct></value>
</member>
<member>
<name>rate_id</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>390.0</double></value>
</member>
<member>
<name>day</name>
<value><string>01/03/2020</string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>ancillary</name>
<value><struct>
<member>
<name>channel_rate_name</name>
<value><string>Standard Rate</string></value>
</member>
</struct></value>
</member>
<member>
<name>rate_id</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>390.0</double></value>
</member>
<member>
<name>day</name>
<value><string>02/03/2020</string></value>
</member>
</struct></value>
</data></array></value>
</member>
<member>
<name>room_id</name>
<value><int>431916</int></value>
</member>
</struct></value>
</data></array></value>
</member>
<member>
<name>customer_name</name>
<value><string>Sebastián Pedro</string></value>
</member>
<member>
<name>date_arrival</name>
<value><string>28/02/2020</string></value>
</member>
<member>
<name>status</name>
<value><int>1</int></value>
</member>
<member>
<name>channel_data</name>
<value><struct>
<member>
<name>addons_embedded</name>
<value><boolean>1</boolean></value>
</member>
<member>
<name>vat_included</name>
<value><int>-1</int></value>
</member>
</struct></value>
</member>
<member>
<name>channel_reservation_code</name>
<value><string>2369807519</string></value>
</member>
<member>
<name>customer_phone</name>
<value><string></string></value>
</member>
<member>
<name>orig_amount</name>
<value><double>1970.0</double></value>
</member>
<member>
<name>men</name>
<value><int>8</int></value>
</member>
<member>
<name>customer_notes</name>
<value><string></string></value>
</member>
<member>
<name>customer_address</name>
<value><string></string></value>
</member>
<member>
<name>device</name>
<value><int>-1</int></value>
</member>
<member>
<name>addons_list</name>
<value><array><data>
</data></array></value>
</member>
<member>
<name>status_reason</name>
<value><string></string></value>
</member>
<member>
<name>roomnight</name>
<value><int>36</int></value>
</member>
<member>
<name>boards</name>
<value><string></string></value>
</member>
<member>
<name>customer_language</name>
<value><int>2</int></value>
</member>
<member>
<name>fount</name>
<value><string></string></value>
</member>
<member>
<name>customer_zip</name>
<value><string></string></value>
</member>
<member>
<name>amount</name>
<value><double>1970.0</double></value>
</member>
<member>
<name>id_woodoo</name>
<value><int>169684</int></value>
</member>
<member>
<name>cc_info</name>
<value><int>0</int></value>
</member>
<member>
<name>room_opportunities</name>
<value><int>0</int></value>
</member>
<member>
<name>customer_language_iso</name>
<value><string>en</string></value>
</member>
</struct></value>
</data></array></value>
</data></array></value>
</param>
</params>
</methodResponse>";
      
    }