<?php

function xmlTest()
    {
      return "<?xml version='1.0'?>
<methodResponse>
<params>
<param>
<value><array><data>
<value><int>0</int></value>
<value><array><data>
<value><struct>
<member>
<name>anchorate</name>
<value><int>0</int></value>
</member>
<member>
<name>name</name>
<value><string>5D</string></value>
</member>
<member>
<name>rtype</name>
<value><int>1</int></value>
</member>
<member>
<name>dec_avail</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>999.0</double></value>
</member>
<member>
<name>men</name>
<value><int>1</int></value>
</member>
<member>
<name>subroom</name>
<value><int>432360</int></value>
</member>
<member>
<name>occupancy</name>
<value><int>1</int></value>
</member>
<member>
<name>id</name>
<value><int>432364</int></value>
</member>
<member>
<name>min_price</name>
<value><int>0</int></value>
</member>
<member>
<name>board</name>
<value><string>nb</string></value>
</member>
<member>
<name>availability</name>
<value><int>2</int></value>
</member>
<member>
<name>woodoo</name>
<value><int>0</int></value>
</member>
<member>
<name>shortname</name>
<value><string>5D</string></value>
</member>
<member>
<name>max_price</name>
<value><int>0</int></value>
</member>
<member>
<name>rtype_name</name>
<value><string>Room</string></value>
</member>
<member>
<name>children</name>
<value><int>0</int></value>
</member>
<member>
<name>boards</name>
<value><string></string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>anchorate</name>
<value><int>0</int></value>
</member>
<member>
<name>name</name>
<value><string>5F</string></value>
</member>
<member>
<name>rtype</name>
<value><int>1</int></value>
</member>
<member>
<name>dec_avail</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>999.0</double></value>
</member>
<member>
<name>men</name>
<value><int>1</int></value>
</member>
<member>
<name>subroom</name>
<value><int>432360</int></value>
</member>
<member>
<name>occupancy</name>
<value><int>1</int></value>
</member>
<member>
<name>id</name>
<value><int>432365</int></value>
</member>
<member>
<name>min_price</name>
<value><int>0</int></value>
</member>
<member>
<name>board</name>
<value><string>nb</string></value>
</member>
<member>
<name>availability</name>
<value><int>2</int></value>
</member>
<member>
<name>woodoo</name>
<value><int>0</int></value>
</member>
<member>
<name>shortname</name>
<value><string>5F</string></value>
</member>
<member>
<name>max_price</name>
<value><int>0</int></value>
</member>
<member>
<name>rtype_name</name>
<value><string>Room</string></value>
</member>
<member>
<name>children</name>
<value><int>0</int></value>
</member>
<member>
<name>boards</name>
<value><string></string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>anchorate</name>
<value><int>0</int></value>
</member>
<member>
<name>name</name>
<value><string>8T</string></value>
</member>
<member>
<name>rtype</name>
<value><int>1</int></value>
</member>
<member>
<name>dec_avail</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>999.0</double></value>
</member>
<member>
<name>men</name>
<value><int>1</int></value>
</member>
<member>
<name>subroom</name>
<value><int>432360</int></value>
</member>
<member>
<name>occupancy</name>
<value><int>1</int></value>
</member>
<member>
<name>id</name>
<value><int>432366</int></value>
</member>
<member>
<name>min_price</name>
<value><int>0</int></value>
</member>
<member>
<name>board</name>
<value><string>nb</string></value>
</member>
<member>
<name>availability</name>
<value><int>2</int></value>
</member>
<member>
<name>woodoo</name>
<value><int>0</int></value>
</member>
<member>
<name>shortname</name>
<value><string>8T</string></value>
</member>
<member>
<name>max_price</name>
<value><int>0</int></value>
</member>
<member>
<name>rtype_name</name>
<value><string>Room</string></value>
</member>
<member>
<name>children</name>
<value><int>0</int></value>
</member>
<member>
<name>boards</name>
<value><string></string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>anchorate</name>
<value><int>0</int></value>
</member>
<member>
<name>name</name>
<value><string>DOS DORM LUJO</string></value>
</member>
<member>
<name>rtype</name>
<value><int>1</int></value>
</member>
<member>
<name>dec_avail</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>999.0</double></value>
</member>
<member>
<name>men</name>
<value><int>6</int></value>
</member>
<member>
<name>subroom</name>
<value><int>0</int></value>
</member>
<member>
<name>occupancy</name>
<value><int>6</int></value>
</member>
<member>
<name>id</name>
<value><int>432360</int></value>
</member>
<member>
<name>min_price</name>
<value><int>0</int></value>
</member>
<member>
<name>board</name>
<value><string>nb</string></value>
</member>
<member>
<name>availability</name>
<value><int>5</int></value>
</member>
<member>
<name>woodoo</name>
<value><int>0</int></value>
</member>
<member>
<name>shortname</name>
<value><string>DDL</string></value>
</member>
<member>
<name>max_price</name>
<value><int>0</int></value>
</member>
<member>
<name>rtype_name</name>
<value><string>Room</string></value>
</member>
<member>
<name>children</name>
<value><int>0</int></value>
</member>
<member>
<name>boards</name>
<value><string></string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>anchorate</name>
<value><int>0</int></value>
</member>
<member>
<name>name</name>
<value><string>8D</string></value>
</member>
<member>
<name>rtype</name>
<value><int>1</int></value>
</member>
<member>
<name>dec_avail</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>999.0</double></value>
</member>
<member>
<name>men</name>
<value><int>4</int></value>
</member>
<member>
<name>subroom</name>
<value><int>432360</int></value>
</member>
<member>
<name>occupancy</name>
<value><int>10</int></value>
</member>
<member>
<name>id</name>
<value><int>432361</int></value>
</member>
<member>
<name>min_price</name>
<value><int>0</int></value>
</member>
<member>
<name>board</name>
<value><string>nb</string></value>
</member>
<member>
<name>availability</name>
<value><int>2</int></value>
</member>
<member>
<name>woodoo</name>
<value><int>0</int></value>
</member>
<member>
<name>shortname</name>
<value><string>8D</string></value>
</member>
<member>
<name>max_price</name>
<value><int>0</int></value>
</member>
<member>
<name>rtype_name</name>
<value><string>Room</string></value>
</member>
<member>
<name>children</name>
<value><int>6</int></value>
</member>
<member>
<name>boards</name>
<value><string></string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>anchorate</name>
<value><int>0</int></value>
</member>
<member>
<name>name</name>
<value><string>Javier Gil 7J</string></value>
</member>
<member>
<name>rtype</name>
<value><int>1</int></value>
</member>
<member>
<name>dec_avail</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>450.0</double></value>
</member>
<member>
<name>men</name>
<value><int>9</int></value>
</member>
<member>
<name>subroom</name>
<value><int>0</int></value>
</member>
<member>
<name>occupancy</name>
<value><int>9</int></value>
</member>
<member>
<name>id</name>
<value><int>431916</int></value>
</member>
<member>
<name>min_price</name>
<value><int>0</int></value>
</member>
<member>
<name>board</name>
<value><string>nb</string></value>
</member>
<member>
<name>availability</name>
<value><int>1</int></value>
</member>
<member>
<name>woodoo</name>
<value><int>0</int></value>
</member>
<member>
<name>shortname</name>
<value><string>7J</string></value>
</member>
<member>
<name>max_price</name>
<value><int>0</int></value>
</member>
<member>
<name>rtype_name</name>
<value><string>Room</string></value>
</member>
<member>
<name>children</name>
<value><int>0</int></value>
</member>
<member>
<name>boards</name>
<value><string></string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>anchorate</name>
<value><int>0</int></value>
</member>
<member>
<name>name</name>
<value><string>Atico a pie de pista (3 dormitorios + 2 baños)</string></value>
</member>
<member>
<name>rtype</name>
<value><int>2</int></value>
</member>
<member>
<name>dec_avail</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>300.0</double></value>
</member>
<member>
<name>men</name>
<value><int>6</int></value>
</member>
<member>
<name>subroom</name>
<value><int>0</int></value>
</member>
<member>
<name>occupancy</name>
<value><int>6</int></value>
</member>
<member>
<name>id</name>
<value><int>432606</int></value>
</member>
<member>
<name>min_price</name>
<value><int>0</int></value>
</member>
<member>
<name>board</name>
<value><string>nb</string></value>
</member>
<member>
<name>availability</name>
<value><int>1</int></value>
</member>
<member>
<name>woodoo</name>
<value><int>0</int></value>
</member>
<member>
<name>shortname</name>
<value><string>9R</string></value>
</member>
<member>
<name>max_price</name>
<value><int>0</int></value>
</member>
<member>
<name>rtype_name</name>
<value><string>Apartment</string></value>
</member>
<member>
<name>children</name>
<value><int>0</int></value>
</member>
<member>
<name>boards</name>
<value><string></string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>anchorate</name>
<value><int>0</int></value>
</member>
<member>
<name>name</name>
<value><string>Ático precioso con piscina (10 </string></value>
</member>
<member>
<name>rtype</name>
<value><int>1</int></value>
</member>
<member>
<name>dec_avail</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>300.0</double></value>
</member>
<member>
<name>men</name>
<value><int>8</int></value>
</member>
<member>
<name>subroom</name>
<value><int>0</int></value>
</member>
<member>
<name>occupancy</name>
<value><int>8</int></value>
</member>
<member>
<name>id</name>
<value><int>432610</int></value>
</member>
<member>
<name>min_price</name>
<value><int>0</int></value>
</member>
<member>
<name>board</name>
<value><string>nb</string></value>
</member>
<member>
<name>availability</name>
<value><int>1</int></value>
</member>
<member>
<name>woodoo</name>
<value><int>0</int></value>
</member>
<member>
<name>shortname</name>
<value><string>10I</string></value>
</member>
<member>
<name>max_price</name>
<value><int>0</int></value>
</member>
<member>
<name>rtype_name</name>
<value><string>Room</string></value>
</member>
<member>
<name>children</name>
<value><int>0</int></value>
</member>
<member>
<name>boards</name>
<value><string></string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>anchorate</name>
<value><int>0</int></value>
</member>
<member>
<name>name</name>
<value><string>Zona baja recién Reformado </string></value>
</member>
<member>
<name>rtype</name>
<value><int>1</int></value>
</member>
<member>
<name>dec_avail</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>300.0</double></value>
</member>
<member>
<name>men</name>
<value><int>5</int></value>
</member>
<member>
<name>subroom</name>
<value><int>0</int></value>
</member>
<member>
<name>occupancy</name>
<value><int>5</int></value>
</member>
<member>
<name>id</name>
<value><int>432611</int></value>
</member>
<member>
<name>min_price</name>
<value><int>0</int></value>
</member>
<member>
<name>board</name>
<value><string>nb</string></value>
</member>
<member>
<name>availability</name>
<value><int>1</int></value>
</member>
<member>
<name>woodoo</name>
<value><int>0</int></value>
</member>
<member>
<name>shortname</name>
<value><string>GORB</string></value>
</member>
<member>
<name>max_price</name>
<value><int>0</int></value>
</member>
<member>
<name>rtype_name</name>
<value><string>Room</string></value>
</member>
<member>
<name>children</name>
<value><int>0</int></value>
</member>
<member>
<name>boards</name>
<value><string></string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>anchorate</name>
<value><int>0</int></value>
</member>
<member>
<name>name</name>
<value><string>Duplex MiramarSki </string></value>
</member>
<member>
<name>rtype</name>
<value><int>1</int></value>
</member>
<member>
<name>dec_avail</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>300.0</double></value>
</member>
<member>
<name>men</name>
<value><int>12</int></value>
</member>
<member>
<name>subroom</name>
<value><int>0</int></value>
</member>
<member>
<name>occupancy</name>
<value><int>12</int></value>
</member>
<member>
<name>id</name>
<value><int>432612</int></value>
</member>
<member>
<name>min_price</name>
<value><int>0</int></value>
</member>
<member>
<name>board</name>
<value><string>nb</string></value>
</member>
<member>
<name>availability</name>
<value><int>1</int></value>
</member>
<member>
<name>woodoo</name>
<value><int>0</int></value>
</member>
<member>
<name>shortname</name>
<value><string>9F</string></value>
</member>
<member>
<name>max_price</name>
<value><int>0</int></value>
</member>
<member>
<name>rtype_name</name>
<value><string>Room</string></value>
</member>
<member>
<name>children</name>
<value><int>0</int></value>
</member>
<member>
<name>boards</name>
<value><string></string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>anchorate</name>
<value><int>0</int></value>
</member>
<member>
<name>name</name>
<value><string>Chalet Adosado zona med/baja </string></value>
</member>
<member>
<name>rtype</name>
<value><int>1</int></value>
</member>
<member>
<name>dec_avail</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>300.0</double></value>
</member>
<member>
<name>men</name>
<value><int>6</int></value>
</member>
<member>
<name>subroom</name>
<value><int>0</int></value>
</member>
<member>
<name>occupancy</name>
<value><int>6</int></value>
</member>
<member>
<name>id</name>
<value><int>432613</int></value>
</member>
<member>
<name>min_price</name>
<value><int>0</int></value>
</member>
<member>
<name>board</name>
<value><string>nb</string></value>
</member>
<member>
<name>availability</name>
<value><int>1</int></value>
</member>
<member>
<name>woodoo</name>
<value><int>0</int></value>
</member>
<member>
<name>shortname</name>
<value><string>CHLT</string></value>
</member>
<member>
<name>max_price</name>
<value><int>0</int></value>
</member>
<member>
<name>rtype_name</name>
<value><string>Room</string></value>
</member>
<member>
<name>children</name>
<value><int>0</int></value>
</member>
<member>
<name>boards</name>
<value><string></string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>anchorate</name>
<value><int>0</int></value>
</member>
<member>
<name>name</name>
<value><string>[DDS] DOS DORM STANDAR</string></value>
</member>
<member>
<name>rtype</name>
<value><int>1</int></value>
</member>
<member>
<name>dec_avail</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>300.0</double></value>
</member>
<member>
<name>men</name>
<value><int>6</int></value>
</member>
<member>
<name>subroom</name>
<value><int>0</int></value>
</member>
<member>
<name>occupancy</name>
<value><int>6</int></value>
</member>
<member>
<name>id</name>
<value><int>432614</int></value>
</member>
<member>
<name>min_price</name>
<value><int>0</int></value>
</member>
<member>
<name>board</name>
<value><string>nb</string></value>
</member>
<member>
<name>availability</name>
<value><int>10</int></value>
</member>
<member>
<name>woodoo</name>
<value><int>0</int></value>
</member>
<member>
<name>shortname</name>
<value><string>DDS</string></value>
</member>
<member>
<name>max_price</name>
<value><int>0</int></value>
</member>
<member>
<name>rtype_name</name>
<value><string>Room</string></value>
</member>
<member>
<name>children</name>
<value><int>0</int></value>
</member>
<member>
<name>boards</name>
<value><string></string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>anchorate</name>
<value><int>0</int></value>
</member>
<member>
<name>name</name>
<value><string>4P</string></value>
</member>
<member>
<name>rtype</name>
<value><int>1</int></value>
</member>
<member>
<name>dec_avail</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>300.0</double></value>
</member>
<member>
<name>men</name>
<value><int>6</int></value>
</member>
<member>
<name>subroom</name>
<value><int>432614</int></value>
</member>
<member>
<name>occupancy</name>
<value><int>7</int></value>
</member>
<member>
<name>id</name>
<value><int>432615</int></value>
</member>
<member>
<name>min_price</name>
<value><int>0</int></value>
</member>
<member>
<name>board</name>
<value><string>nb</string></value>
</member>
<member>
<name>availability</name>
<value><int>2</int></value>
</member>
<member>
<name>woodoo</name>
<value><int>0</int></value>
</member>
<member>
<name>shortname</name>
<value><string>4P</string></value>
</member>
<member>
<name>max_price</name>
<value><int>0</int></value>
</member>
<member>
<name>rtype_name</name>
<value><string>Room</string></value>
</member>
<member>
<name>children</name>
<value><int>1</int></value>
</member>
<member>
<name>boards</name>
<value><string></string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>anchorate</name>
<value><int>0</int></value>
</member>
<member>
<name>name</name>
<value><string>7P</string></value>
</member>
<member>
<name>rtype</name>
<value><int>1</int></value>
</member>
<member>
<name>dec_avail</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>300.0</double></value>
</member>
<member>
<name>men</name>
<value><int>6</int></value>
</member>
<member>
<name>subroom</name>
<value><int>432614</int></value>
</member>
<member>
<name>occupancy</name>
<value><int>7</int></value>
</member>
<member>
<name>id</name>
<value><int>432616</int></value>
</member>
<member>
<name>min_price</name>
<value><int>0</int></value>
</member>
<member>
<name>board</name>
<value><string>nb</string></value>
</member>
<member>
<name>availability</name>
<value><int>2</int></value>
</member>
<member>
<name>woodoo</name>
<value><int>0</int></value>
</member>
<member>
<name>shortname</name>
<value><string>7P</string></value>
</member>
<member>
<name>max_price</name>
<value><int>0</int></value>
</member>
<member>
<name>rtype_name</name>
<value><string>Room</string></value>
</member>
<member>
<name>children</name>
<value><int>1</int></value>
</member>
<member>
<name>boards</name>
<value><string></string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>anchorate</name>
<value><int>0</int></value>
</member>
<member>
<name>name</name>
<value><string>4N</string></value>
</member>
<member>
<name>rtype</name>
<value><int>1</int></value>
</member>
<member>
<name>dec_avail</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>300.0</double></value>
</member>
<member>
<name>men</name>
<value><int>6</int></value>
</member>
<member>
<name>subroom</name>
<value><int>432614</int></value>
</member>
<member>
<name>occupancy</name>
<value><int>7</int></value>
</member>
<member>
<name>id</name>
<value><int>432617</int></value>
</member>
<member>
<name>min_price</name>
<value><int>0</int></value>
</member>
<member>
<name>board</name>
<value><string>nb</string></value>
</member>
<member>
<name>availability</name>
<value><int>2</int></value>
</member>
<member>
<name>woodoo</name>
<value><int>0</int></value>
</member>
<member>
<name>shortname</name>
<value><string>4N</string></value>
</member>
<member>
<name>max_price</name>
<value><int>0</int></value>
</member>
<member>
<name>rtype_name</name>
<value><string>Room</string></value>
</member>
<member>
<name>children</name>
<value><int>1</int></value>
</member>
<member>
<name>boards</name>
<value><string></string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>anchorate</name>
<value><int>0</int></value>
</member>
<member>
<name>name</name>
<value><string>G8</string></value>
</member>
<member>
<name>rtype</name>
<value><int>1</int></value>
</member>
<member>
<name>dec_avail</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>300.0</double></value>
</member>
<member>
<name>men</name>
<value><int>6</int></value>
</member>
<member>
<name>subroom</name>
<value><int>432614</int></value>
</member>
<member>
<name>occupancy</name>
<value><int>7</int></value>
</member>
<member>
<name>id</name>
<value><int>432618</int></value>
</member>
<member>
<name>min_price</name>
<value><int>0</int></value>
</member>
<member>
<name>board</name>
<value><string>nb</string></value>
</member>
<member>
<name>availability</name>
<value><int>2</int></value>
</member>
<member>
<name>woodoo</name>
<value><int>0</int></value>
</member>
<member>
<name>shortname</name>
<value><string>G8</string></value>
</member>
<member>
<name>max_price</name>
<value><int>0</int></value>
</member>
<member>
<name>rtype_name</name>
<value><string>Room</string></value>
</member>
<member>
<name>children</name>
<value><int>1</int></value>
</member>
<member>
<name>boards</name>
<value><string></string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>anchorate</name>
<value><int>0</int></value>
</member>
<member>
<name>name</name>
<value><string>G6</string></value>
</member>
<member>
<name>rtype</name>
<value><int>1</int></value>
</member>
<member>
<name>dec_avail</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>300.0</double></value>
</member>
<member>
<name>men</name>
<value><int>6</int></value>
</member>
<member>
<name>subroom</name>
<value><int>432614</int></value>
</member>
<member>
<name>occupancy</name>
<value><int>7</int></value>
</member>
<member>
<name>id</name>
<value><int>432619</int></value>
</member>
<member>
<name>min_price</name>
<value><int>0</int></value>
</member>
<member>
<name>board</name>
<value><string>nb</string></value>
</member>
<member>
<name>availability</name>
<value><int>2</int></value>
</member>
<member>
<name>woodoo</name>
<value><int>0</int></value>
</member>
<member>
<name>shortname</name>
<value><string>G6</string></value>
</member>
<member>
<name>max_price</name>
<value><int>0</int></value>
</member>
<member>
<name>rtype_name</name>
<value><string>Room</string></value>
</member>
<member>
<name>children</name>
<value><int>1</int></value>
</member>
<member>
<name>boards</name>
<value><string></string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>anchorate</name>
<value><int>0</int></value>
</member>
<member>
<name>name</name>
<value><string>J6</string></value>
</member>
<member>
<name>rtype</name>
<value><int>1</int></value>
</member>
<member>
<name>dec_avail</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>300.0</double></value>
</member>
<member>
<name>men</name>
<value><int>6</int></value>
</member>
<member>
<name>subroom</name>
<value><int>432614</int></value>
</member>
<member>
<name>occupancy</name>
<value><int>7</int></value>
</member>
<member>
<name>id</name>
<value><int>432620</int></value>
</member>
<member>
<name>min_price</name>
<value><int>0</int></value>
</member>
<member>
<name>board</name>
<value><string>nb</string></value>
</member>
<member>
<name>availability</name>
<value><int>2</int></value>
</member>
<member>
<name>woodoo</name>
<value><int>0</int></value>
</member>
<member>
<name>shortname</name>
<value><string>J6</string></value>
</member>
<member>
<name>max_price</name>
<value><int>0</int></value>
</member>
<member>
<name>rtype_name</name>
<value><string>Room</string></value>
</member>
<member>
<name>children</name>
<value><int>1</int></value>
</member>
<member>
<name>boards</name>
<value><string></string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>anchorate</name>
<value><int>0</int></value>
</member>
<member>
<name>name</name>
<value><string>J5</string></value>
</member>
<member>
<name>rtype</name>
<value><int>1</int></value>
</member>
<member>
<name>dec_avail</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>300.0</double></value>
</member>
<member>
<name>men</name>
<value><int>6</int></value>
</member>
<member>
<name>subroom</name>
<value><int>432614</int></value>
</member>
<member>
<name>occupancy</name>
<value><int>7</int></value>
</member>
<member>
<name>id</name>
<value><int>432621</int></value>
</member>
<member>
<name>min_price</name>
<value><int>0</int></value>
</member>
<member>
<name>board</name>
<value><string>nb</string></value>
</member>
<member>
<name>availability</name>
<value><int>2</int></value>
</member>
<member>
<name>woodoo</name>
<value><int>0</int></value>
</member>
<member>
<name>shortname</name>
<value><string>J5</string></value>
</member>
<member>
<name>max_price</name>
<value><int>0</int></value>
</member>
<member>
<name>rtype_name</name>
<value><string>Room</string></value>
</member>
<member>
<name>children</name>
<value><int>1</int></value>
</member>
<member>
<name>boards</name>
<value><string></string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>anchorate</name>
<value><int>0</int></value>
</member>
<member>
<name>name</name>
<value><string>J8</string></value>
</member>
<member>
<name>rtype</name>
<value><int>1</int></value>
</member>
<member>
<name>dec_avail</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>300.0</double></value>
</member>
<member>
<name>men</name>
<value><int>6</int></value>
</member>
<member>
<name>subroom</name>
<value><int>432614</int></value>
</member>
<member>
<name>occupancy</name>
<value><int>7</int></value>
</member>
<member>
<name>id</name>
<value><int>432622</int></value>
</member>
<member>
<name>min_price</name>
<value><int>0</int></value>
</member>
<member>
<name>board</name>
<value><string>nb</string></value>
</member>
<member>
<name>availability</name>
<value><int>2</int></value>
</member>
<member>
<name>woodoo</name>
<value><int>0</int></value>
</member>
<member>
<name>shortname</name>
<value><string>J8</string></value>
</member>
<member>
<name>max_price</name>
<value><int>0</int></value>
</member>
<member>
<name>rtype_name</name>
<value><string>Room</string></value>
</member>
<member>
<name>children</name>
<value><int>1</int></value>
</member>
<member>
<name>boards</name>
<value><string></string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>anchorate</name>
<value><int>0</int></value>
</member>
<member>
<name>name</name>
<value><string>V10</string></value>
</member>
<member>
<name>rtype</name>
<value><int>1</int></value>
</member>
<member>
<name>dec_avail</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>300.0</double></value>
</member>
<member>
<name>men</name>
<value><int>6</int></value>
</member>
<member>
<name>subroom</name>
<value><int>432614</int></value>
</member>
<member>
<name>occupancy</name>
<value><int>7</int></value>
</member>
<member>
<name>id</name>
<value><int>432623</int></value>
</member>
<member>
<name>min_price</name>
<value><int>0</int></value>
</member>
<member>
<name>board</name>
<value><string>nb</string></value>
</member>
<member>
<name>availability</name>
<value><int>2</int></value>
</member>
<member>
<name>woodoo</name>
<value><int>0</int></value>
</member>
<member>
<name>shortname</name>
<value><string>V10</string></value>
</member>
<member>
<name>max_price</name>
<value><int>0</int></value>
</member>
<member>
<name>rtype_name</name>
<value><string>Room</string></value>
</member>
<member>
<name>children</name>
<value><int>1</int></value>
</member>
<member>
<name>boards</name>
<value><string></string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>anchorate</name>
<value><int>0</int></value>
</member>
<member>
<name>name</name>
<value><string>(ST-L) ESTUDIOS LUJO</string></value>
</member>
<member>
<name>rtype</name>
<value><int>1</int></value>
</member>
<member>
<name>dec_avail</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>200.0</double></value>
</member>
<member>
<name>men</name>
<value><int>4</int></value>
</member>
<member>
<name>subroom</name>
<value><int>0</int></value>
</member>
<member>
<name>occupancy</name>
<value><int>4</int></value>
</member>
<member>
<name>id</name>
<value><int>432624</int></value>
</member>
<member>
<name>min_price</name>
<value><int>0</int></value>
</member>
<member>
<name>board</name>
<value><string>nb</string></value>
</member>
<member>
<name>availability</name>
<value><int>5</int></value>
</member>
<member>
<name>woodoo</name>
<value><int>0</int></value>
</member>
<member>
<name>shortname</name>
<value><string>ST-L</string></value>
</member>
<member>
<name>max_price</name>
<value><int>0</int></value>
</member>
<member>
<name>rtype_name</name>
<value><string>Room</string></value>
</member>
<member>
<name>children</name>
<value><int>0</int></value>
</member>
<member>
<name>boards</name>
<value><string></string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>anchorate</name>
<value><int>0</int></value>
</member>
<member>
<name>name</name>
<value><string>5E</string></value>
</member>
<member>
<name>rtype</name>
<value><int>1</int></value>
</member>
<member>
<name>dec_avail</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>200.0</double></value>
</member>
<member>
<name>men</name>
<value><int>4</int></value>
</member>
<member>
<name>subroom</name>
<value><int>432624</int></value>
</member>
<member>
<name>occupancy</name>
<value><int>5</int></value>
</member>
<member>
<name>id</name>
<value><int>432625</int></value>
</member>
<member>
<name>min_price</name>
<value><int>0</int></value>
</member>
<member>
<name>board</name>
<value><string>nb</string></value>
</member>
<member>
<name>availability</name>
<value><int>2</int></value>
</member>
<member>
<name>woodoo</name>
<value><int>0</int></value>
</member>
<member>
<name>shortname</name>
<value><string>5E</string></value>
</member>
<member>
<name>max_price</name>
<value><int>0</int></value>
</member>
<member>
<name>rtype_name</name>
<value><string>Room</string></value>
</member>
<member>
<name>children</name>
<value><int>1</int></value>
</member>
<member>
<name>boards</name>
<value><string></string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>anchorate</name>
<value><int>0</int></value>
</member>
<member>
<name>name</name>
<value><string>9J</string></value>
</member>
<member>
<name>rtype</name>
<value><int>1</int></value>
</member>
<member>
<name>dec_avail</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>200.0</double></value>
</member>
<member>
<name>men</name>
<value><int>4</int></value>
</member>
<member>
<name>subroom</name>
<value><int>432624</int></value>
</member>
<member>
<name>occupancy</name>
<value><int>5</int></value>
</member>
<member>
<name>id</name>
<value><int>432626</int></value>
</member>
<member>
<name>min_price</name>
<value><int>0</int></value>
</member>
<member>
<name>board</name>
<value><string>nb</string></value>
</member>
<member>
<name>availability</name>
<value><int>2</int></value>
</member>
<member>
<name>woodoo</name>
<value><int>0</int></value>
</member>
<member>
<name>shortname</name>
<value><string>9J</string></value>
</member>
<member>
<name>max_price</name>
<value><int>0</int></value>
</member>
<member>
<name>rtype_name</name>
<value><string>Room</string></value>
</member>
<member>
<name>children</name>
<value><int>1</int></value>
</member>
<member>
<name>boards</name>
<value><string></string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>anchorate</name>
<value><int>0</int></value>
</member>
<member>
<name>name</name>
<value><string>9S</string></value>
</member>
<member>
<name>rtype</name>
<value><int>1</int></value>
</member>
<member>
<name>dec_avail</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>200.0</double></value>
</member>
<member>
<name>men</name>
<value><int>4</int></value>
</member>
<member>
<name>subroom</name>
<value><int>432624</int></value>
</member>
<member>
<name>occupancy</name>
<value><int>5</int></value>
</member>
<member>
<name>id</name>
<value><int>432627</int></value>
</member>
<member>
<name>min_price</name>
<value><int>0</int></value>
</member>
<member>
<name>board</name>
<value><string>nb</string></value>
</member>
<member>
<name>availability</name>
<value><int>2</int></value>
</member>
<member>
<name>woodoo</name>
<value><int>0</int></value>
</member>
<member>
<name>shortname</name>
<value><string>9S</string></value>
</member>
<member>
<name>max_price</name>
<value><int>0</int></value>
</member>
<member>
<name>rtype_name</name>
<value><string>Room</string></value>
</member>
<member>
<name>children</name>
<value><int>1</int></value>
</member>
<member>
<name>boards</name>
<value><string></string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>anchorate</name>
<value><int>0</int></value>
</member>
<member>
<name>name</name>
<value><string>S7</string></value>
</member>
<member>
<name>rtype</name>
<value><int>1</int></value>
</member>
<member>
<name>dec_avail</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>200.0</double></value>
</member>
<member>
<name>men</name>
<value><int>4</int></value>
</member>
<member>
<name>subroom</name>
<value><int>432624</int></value>
</member>
<member>
<name>occupancy</name>
<value><int>5</int></value>
</member>
<member>
<name>id</name>
<value><int>432628</int></value>
</member>
<member>
<name>min_price</name>
<value><int>0</int></value>
</member>
<member>
<name>board</name>
<value><string>nb</string></value>
</member>
<member>
<name>availability</name>
<value><int>2</int></value>
</member>
<member>
<name>woodoo</name>
<value><int>0</int></value>
</member>
<member>
<name>shortname</name>
<value><string>S7</string></value>
</member>
<member>
<name>max_price</name>
<value><int>0</int></value>
</member>
<member>
<name>rtype_name</name>
<value><string>Room</string></value>
</member>
<member>
<name>children</name>
<value><int>1</int></value>
</member>
<member>
<name>boards</name>
<value><string></string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>anchorate</name>
<value><int>0</int></value>
</member>
<member>
<name>name</name>
<value><string>O5</string></value>
</member>
<member>
<name>rtype</name>
<value><int>1</int></value>
</member>
<member>
<name>dec_avail</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>200.0</double></value>
</member>
<member>
<name>men</name>
<value><int>4</int></value>
</member>
<member>
<name>subroom</name>
<value><int>432624</int></value>
</member>
<member>
<name>occupancy</name>
<value><int>5</int></value>
</member>
<member>
<name>id</name>
<value><int>432629</int></value>
</member>
<member>
<name>min_price</name>
<value><int>0</int></value>
</member>
<member>
<name>board</name>
<value><string>nb</string></value>
</member>
<member>
<name>availability</name>
<value><int>2</int></value>
</member>
<member>
<name>woodoo</name>
<value><int>0</int></value>
</member>
<member>
<name>shortname</name>
<value><string>O5</string></value>
</member>
<member>
<name>max_price</name>
<value><int>0</int></value>
</member>
<member>
<name>rtype_name</name>
<value><string>Room</string></value>
</member>
<member>
<name>children</name>
<value><int>1</int></value>
</member>
<member>
<name>boards</name>
<value><string></string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>anchorate</name>
<value><int>0</int></value>
</member>
<member>
<name>name</name>
<value><string>(ST-S) ESTUDIOS ESTANDAR</string></value>
</member>
<member>
<name>rtype</name>
<value><int>1</int></value>
</member>
<member>
<name>dec_avail</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>200.0</double></value>
</member>
<member>
<name>men</name>
<value><int>4</int></value>
</member>
<member>
<name>subroom</name>
<value><int>0</int></value>
</member>
<member>
<name>occupancy</name>
<value><int>4</int></value>
</member>
<member>
<name>id</name>
<value><int>432630</int></value>
</member>
<member>
<name>min_price</name>
<value><int>0</int></value>
</member>
<member>
<name>board</name>
<value><string>nb</string></value>
</member>
<member>
<name>availability</name>
<value><int>7</int></value>
</member>
<member>
<name>woodoo</name>
<value><int>0</int></value>
</member>
<member>
<name>shortname</name>
<value><string>ST-S</string></value>
</member>
<member>
<name>max_price</name>
<value><int>0</int></value>
</member>
<member>
<name>rtype_name</name>
<value><string>Room</string></value>
</member>
<member>
<name>children</name>
<value><int>0</int></value>
</member>
<member>
<name>boards</name>
<value><string></string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>anchorate</name>
<value><int>0</int></value>
</member>
<member>
<name>name</name>
<value><string>U7</string></value>
</member>
<member>
<name>rtype</name>
<value><int>1</int></value>
</member>
<member>
<name>dec_avail</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>200.0</double></value>
</member>
<member>
<name>men</name>
<value><int>4</int></value>
</member>
<member>
<name>subroom</name>
<value><int>432630</int></value>
</member>
<member>
<name>occupancy</name>
<value><int>5</int></value>
</member>
<member>
<name>id</name>
<value><int>432631</int></value>
</member>
<member>
<name>min_price</name>
<value><int>0</int></value>
</member>
<member>
<name>board</name>
<value><string>nb</string></value>
</member>
<member>
<name>availability</name>
<value><int>2</int></value>
</member>
<member>
<name>woodoo</name>
<value><int>0</int></value>
</member>
<member>
<name>shortname</name>
<value><string>U7</string></value>
</member>
<member>
<name>max_price</name>
<value><int>0</int></value>
</member>
<member>
<name>rtype_name</name>
<value><string>Room</string></value>
</member>
<member>
<name>children</name>
<value><int>1</int></value>
</member>
<member>
<name>boards</name>
<value><string></string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>anchorate</name>
<value><int>0</int></value>
</member>
<member>
<name>name</name>
<value><string>H7</string></value>
</member>
<member>
<name>rtype</name>
<value><int>1</int></value>
</member>
<member>
<name>dec_avail</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>200.0</double></value>
</member>
<member>
<name>men</name>
<value><int>4</int></value>
</member>
<member>
<name>subroom</name>
<value><int>432630</int></value>
</member>
<member>
<name>occupancy</name>
<value><int>5</int></value>
</member>
<member>
<name>id</name>
<value><int>432632</int></value>
</member>
<member>
<name>min_price</name>
<value><int>0</int></value>
</member>
<member>
<name>board</name>
<value><string>nb</string></value>
</member>
<member>
<name>availability</name>
<value><int>2</int></value>
</member>
<member>
<name>woodoo</name>
<value><int>0</int></value>
</member>
<member>
<name>shortname</name>
<value><string>H7</string></value>
</member>
<member>
<name>max_price</name>
<value><int>0</int></value>
</member>
<member>
<name>rtype_name</name>
<value><string>Room</string></value>
</member>
<member>
<name>children</name>
<value><int>1</int></value>
</member>
<member>
<name>boards</name>
<value><string></string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>anchorate</name>
<value><int>0</int></value>
</member>
<member>
<name>name</name>
<value><string>5K</string></value>
</member>
<member>
<name>rtype</name>
<value><int>1</int></value>
</member>
<member>
<name>dec_avail</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>200.0</double></value>
</member>
<member>
<name>men</name>
<value><int>4</int></value>
</member>
<member>
<name>subroom</name>
<value><int>432630</int></value>
</member>
<member>
<name>occupancy</name>
<value><int>5</int></value>
</member>
<member>
<name>id</name>
<value><int>432633</int></value>
</member>
<member>
<name>min_price</name>
<value><int>0</int></value>
</member>
<member>
<name>board</name>
<value><string>nb</string></value>
</member>
<member>
<name>availability</name>
<value><int>2</int></value>
</member>
<member>
<name>woodoo</name>
<value><int>0</int></value>
</member>
<member>
<name>shortname</name>
<value><string>5K</string></value>
</member>
<member>
<name>max_price</name>
<value><int>0</int></value>
</member>
<member>
<name>rtype_name</name>
<value><string>Room</string></value>
</member>
<member>
<name>children</name>
<value><int>1</int></value>
</member>
<member>
<name>boards</name>
<value><string></string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>anchorate</name>
<value><int>0</int></value>
</member>
<member>
<name>name</name>
<value><string>6K</string></value>
</member>
<member>
<name>rtype</name>
<value><int>1</int></value>
</member>
<member>
<name>dec_avail</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>200.0</double></value>
</member>
<member>
<name>men</name>
<value><int>4</int></value>
</member>
<member>
<name>subroom</name>
<value><int>432630</int></value>
</member>
<member>
<name>occupancy</name>
<value><int>5</int></value>
</member>
<member>
<name>id</name>
<value><int>432634</int></value>
</member>
<member>
<name>min_price</name>
<value><int>0</int></value>
</member>
<member>
<name>board</name>
<value><string>nb</string></value>
</member>
<member>
<name>availability</name>
<value><int>2</int></value>
</member>
<member>
<name>woodoo</name>
<value><int>0</int></value>
</member>
<member>
<name>shortname</name>
<value><string>6K</string></value>
</member>
<member>
<name>max_price</name>
<value><int>0</int></value>
</member>
<member>
<name>rtype_name</name>
<value><string>Room</string></value>
</member>
<member>
<name>children</name>
<value><int>1</int></value>
</member>
<member>
<name>boards</name>
<value><string></string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>anchorate</name>
<value><int>0</int></value>
</member>
<member>
<name>name</name>
<value><string>V8</string></value>
</member>
<member>
<name>rtype</name>
<value><int>1</int></value>
</member>
<member>
<name>dec_avail</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>200.0</double></value>
</member>
<member>
<name>men</name>
<value><int>4</int></value>
</member>
<member>
<name>subroom</name>
<value><int>432630</int></value>
</member>
<member>
<name>occupancy</name>
<value><int>5</int></value>
</member>
<member>
<name>id</name>
<value><int>432635</int></value>
</member>
<member>
<name>min_price</name>
<value><int>0</int></value>
</member>
<member>
<name>board</name>
<value><string>nb</string></value>
</member>
<member>
<name>availability</name>
<value><int>2</int></value>
</member>
<member>
<name>woodoo</name>
<value><int>0</int></value>
</member>
<member>
<name>shortname</name>
<value><string>V8</string></value>
</member>
<member>
<name>max_price</name>
<value><int>0</int></value>
</member>
<member>
<name>rtype_name</name>
<value><string>Room</string></value>
</member>
<member>
<name>children</name>
<value><int>1</int></value>
</member>
<member>
<name>boards</name>
<value><string></string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>anchorate</name>
<value><int>0</int></value>
</member>
<member>
<name>name</name>
<value><string>B5</string></value>
</member>
<member>
<name>rtype</name>
<value><int>1</int></value>
</member>
<member>
<name>dec_avail</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>200.0</double></value>
</member>
<member>
<name>men</name>
<value><int>4</int></value>
</member>
<member>
<name>subroom</name>
<value><int>432630</int></value>
</member>
<member>
<name>occupancy</name>
<value><int>5</int></value>
</member>
<member>
<name>id</name>
<value><int>432636</int></value>
</member>
<member>
<name>min_price</name>
<value><int>0</int></value>
</member>
<member>
<name>board</name>
<value><string>nb</string></value>
</member>
<member>
<name>availability</name>
<value><int>2</int></value>
</member>
<member>
<name>woodoo</name>
<value><int>0</int></value>
</member>
<member>
<name>shortname</name>
<value><string>B5</string></value>
</member>
<member>
<name>max_price</name>
<value><int>0</int></value>
</member>
<member>
<name>rtype_name</name>
<value><string>Room</string></value>
</member>
<member>
<name>children</name>
<value><int>1</int></value>
</member>
<member>
<name>boards</name>
<value><string></string></value>
</member>
</struct></value>
<value><struct>
<member>
<name>anchorate</name>
<value><int>0</int></value>
</member>
<member>
<name>name</name>
<value><string>8F</string></value>
</member>
<member>
<name>rtype</name>
<value><int>1</int></value>
</member>
<member>
<name>dec_avail</name>
<value><int>0</int></value>
</member>
<member>
<name>price</name>
<value><double>999.0</double></value>
</member>
<member>
<name>men</name>
<value><int>4</int></value>
</member>
<member>
<name>subroom</name>
<value><int>432360</int></value>
</member>
<member>
<name>occupancy</name>
<value><int>10</int></value>
</member>
<member>
<name>id</name>
<value><int>432362</int></value>
</member>
<member>
<name>min_price</name>
<value><int>0</int></value>
</member>
<member>
<name>board</name>
<value><string>nb</string></value>
</member>
<member>
<name>availability</name>
<value><int>2</int></value>
</member>
<member>
<name>woodoo</name>
<value><int>0</int></value>
</member>
<member>
<name>shortname</name>
<value><string>8F</string></value>
</member>
<member>
<name>max_price</name>
<value><int>0</int></value>
</member>
<member>
<name>rtype_name</name>
<value><string>Room</string></value>
</member>
<member>
<name>children</name>
<value><int>6</int></value>
</member>
<member>
<name>boards</name>
<value><string></string></value>
</member>
</struct></value>
</data></array></value>
</data></array></value>
</param>
</params>
</methodResponse>";
      
    }